export const ICONS = [
  { name: 'Calendar', label: 'Calendário' },
  { name: 'CalendarCheck', label: 'Agendamento' },
  { name: 'Phone', label: 'Telefone' },
  { name: 'PhoneCall', label: 'Ligação' },
  { name: 'MessageCircle', label: 'Mensagem' },
  { name: 'MessageSquare', label: 'Chat' },
  { name: 'Mail', label: 'E-mail' },
  { name: 'MapPin', label: 'Localização' },
  { name: 'Map', label: 'Mapa' },
  { name: 'Navigation', label: 'Navegação' },
  { name: 'Globe', label: 'Site' },
  { name: 'Link', label: 'Link' },
  { name: 'ExternalLink', label: 'Link externo' },
  { name: 'Instagram', label: 'Instagram' },
  { name: 'Facebook', label: 'Facebook' },
  { name: 'Youtube', label: 'YouTube' },
  { name: 'Linkedin', label: 'LinkedIn' },
  { name: 'Twitter', label: 'Twitter/X' },
  { name: 'Smile', label: 'Sorriso' },
  { name: 'Heart', label: 'Coração' },
  { name: 'Star', label: 'Estrela' },
  { name: 'Award', label: 'Prêmio' },
  { name: 'BadgeCheck', label: 'Verificado' },
  { name: 'ShieldCheck', label: 'Segurança' },
  { name: 'Stethoscope', label: 'Saúde' },
  { name: 'Cross', label: 'Cruz médica' },
  { name: 'ClipboardList', label: 'Lista' },
  { name: 'FileText', label: 'Documento' },
  { name: 'Info', label: 'Informação' },
  { name: 'HelpCircle', label: 'Ajuda' },
  { name: 'ChevronRight', label: 'Seta direita' },
  { name: 'ArrowRight', label: 'Ação' },
  { name: 'Sparkles', label: 'Destaque' },
  { name: 'Zap', label: 'Rápido' },
  { name: 'Gift', label: 'Oferta' },
  { name: 'Tag', label: 'Tag' },
  { name: 'Clock', label: 'Horário' },
  { name: 'Users', label: 'Equipe' },
  { name: 'User', label: 'Usuário' },
  { name: 'Building2', label: 'Clínica' },
  { name: 'Home', label: 'Casa' },
  { name: 'Store', label: 'Loja' },
  { name: 'QrCode', label: 'QR Code' },
  { name: 'Share2', label: 'Compartilhar' },
  { name: 'Download', label: 'Download' },
  { name: 'PlayCircle', label: 'Vídeo' },
  { name: 'Image', label: 'Imagem' },
  { name: 'Camera', label: 'Câmera' },
  { name: 'Mic', label: 'Microfone' },
  { name: 'Headphones', label: 'Podcast' },
  { name: 'WhatsApp', label: 'WhatsApp' },
] as const

export type IconName = (typeof ICONS)[number]['name']
